-- Keybindings for launching apps in Hyper Mode
--

return {
  -- { hotkey, app-path, kbd-layout },
  -- { '`', '/Applications/Safari.app', nil },
  { '1', '/Applications/Microsoft Teams.app', nil },
  -- { '2', '/Applications/zoom.us.app', 'en' },
  -- { '3', '/Applications/DataGrip.app', 'en' },
  { 'space', '/System/Library/CoreServices/Finder.app', 'en' },
  -- { '`', '/System/Applications/Utilities/Terminal.app', 'en' },
  -- { '`', '/Applications/kitty.app', 'en' },
  -- { '`', '/Applications/Alacritty.app', 'en' },
  -- { '`', '/Applications/iTerm.app', 'en' },
  { 'return', '/Applications/Wezterm.app', 'en' },
  { 'a', '/System/Applications/Utilities/Activity Monitor.app', 'en' },
  -- { 'b', '/Applications/Brave Browser.app', nil },
  { 'c', '/Applications/Visual Studio Code.app', 'en' },
  -- { 'd', '/Applications/Docker.app', 'en'},
  -- { 'u', '/Applications/VSCodium.app', 'en' },
  -- { 'f', '/Applications/Firefox.app', nil },
  { '`', '/Applications/Firefox.app', nil },
  -- { 'f', '/Applications/Firefox Developer Edition.app', nil },
  { 'g', '/Applications/Google Chrome.app', nil },
  { 'i', '/Applications/IntelliJ IDEA.app', 'en' },
  -- { 'l', '/Applications/Slack.app', 'en' },
  -- { 'm', '/Applications/Microsoft Outlook.app', 'en' },
  -- { 'm', '/System/Applications/Mail.app', 'en' },
  -- { 'k', '/System/Applications/Calendar.app', 'en' },
  { 'k', '/Applications/KeePassXC.app', 'en' },
  -- { 'o', '/Applications/Opera.app', nil },
  -- { '`', '/Applications/Opera.app', nil },
  -- { 'v', '/Applications/Viber.app', 'uk' },
  -- { 's', '/Applications/Sourcetree.app', 'en' },
  -- { 't', '/Applications/Telegram.app', nil   },
  -- { 'w', '/Applications/WhatsApp.app', 'uk' },
  -- { '`', '/Applications/Vivaldi.app', nil },
  -- { 'x', '/Applications/FBReader.app', 'en' },
  -- { 'r', '/Applications/Grammarly Editor.app', 'en' },
  { '7', '/System/Applications/System Preferences.app', 'en' },
}
