-- Keybindings for launching apps in Hyper Mode
-- V is reserved

return {
  -- { hotkey, app-path, kbd-layout },
  { 'r',      '/Applications/Safari.app',                    nil },
  -- { '`', '/Applications/Safari.app', nil },
  -- { '1', '/Applications/Microsoft Teams (work or school).app', nil },
  -- { '2', '/Applications/zoom.us.app', 'en' },
  { 'space',  '/System/Library/CoreServices/Finder.app',      nil },
  -- { '`', '/System/Applications/Utilities/Terminal.app', 'en' },
  -- { '`', '/Applications/kitty.app', 'en' },
  { '1',      '/Applications/ChatGPT.app',                   'en' },
  { 'return', '/Applications/Wezterm.app',                   'en' },
  -- { 'a', '/System/Applications/Utilities/Activity Monitor.app', 'en' },
  { 'a',      '/Applications/AnythingLLM.app',               'en' },
  { 'b',      '/Applications/Bitwarden.app', nil },
  { 'c',      '/Applications/Visual Studio Code.app',        'en' },
  -- { 'd',      '/Applications/Docker.app',                            'en' },
  -- { 'u', '/Applications/VSCodium.app', 'en' },
  { 'f',      '/Applications/Firefox.app',                   nil },
  -- { 'e', '/Applications/Microsoft Edge.app', nil },
  { '`',      '/Applications/Firefox.app',                   nil },
  -- { 'f', '/Applications/Firefox Developer Edition.app', nil },
  { 'g',      '/Applications/Google Chrome.app',             nil },
  -- { 'i', '/Applications/IntelliJ IDEA.app', 'en' },
  { 'i',      '/Applications/IntelliJ IDEA 2023.3 EAP.app',  'en' },
  { 'd',      '/Applications/DataGrip 2023.3 EAP.app',       'en' },
  -- { 'l', '/Applications/Slack.app', 'en' },
  -- { 'm', '/Applications/Microsoft Outlook.app', 'en' },
  { 'm',      '/System/Applications/Mail.app',               'en' },
  { 'n',      '/Applications/Lens.app',                      'en' },
  -- { 'k', '/System/Applications/Calendar.app', 'en' },с
  { 'o',      '/Applications/Obsidian.app',                   nil },
  -- { '`', '/Applications/Opera.app', nil },
  -- { 'v', '/Applications/Viber.app', 'uk' },
  -- { 's', '/Applications/Sourcetree.app', 'en' },
  { 's',      '/Applications/Signal.app',                     nil },
  { 't',      '/Applications/Microsoft Teams.app',           nil },
  -- { 't', '/Applications/Telegram.app', nil   },
  { 'w',      '/Applications/WhatsApp.app',                   'uk' },
  -- { '`', '/Applications/Vivaldi.app', nil },
  -- { 'x', '/Applications/FBReader.app', 'en' },
  -- { 'r', '/Applications/Grammarly Editor.app', 'en' },
  -- { 'z', '/Applications/Zed.app', 'en' },
  { 'z',      '/Applications/Zed Preview.app',                'en' },
  { '=',      '/System/Applications/System Settings.app',     'en' },
}
